server:
  port: ${SERVER_PORT}
Spring:
  application:
    name: ${APP_NAME}
eureka:
  instance:
    hostname: ${HOSTNAME}
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka